spring: 
  application: 
    name: ${APP_NAME:Genshin Impact Project}
  datasource:
    url: jdbc:hsqdb:file:testdb
    username: sa
    password:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    # HikariCP
    hikari:
      auto-commit: false
      connection-timeout: 3000
      validation-timeout: 3000
      max-lifetime: 60000
      maximum-pool-size: 20
      minimum-idle: 1

server:
  port: ${APP_PORT:8080}

genshin:
    cookies: UM_distinctid=1785795bf2678-09bd851147d029-2542793a-49a10-1785795bf271b3; _MHYUUID=94dd314e-fd51-4c24-8a97-7e8416d5a24f; ltoken=UsSzYPwOZSSrS4FILImXL4vgp7ntMCgSKTmHt8AP; ltuid=239925102; account_id=239925102; login_ticket=T3eGQbIR6N0LgrIsFWr5KYUNUJT91rgbaRYWR5yY; cookie_token=kLl1Z5WcwAOsrKeeqR3hFBgRQjZ5QrfK601A3gL1
    bbsheader:
      ds: ""
      x-rpc-app-version: "2.2.1"
      cookies: UM_distinctid=1785795bf2678-09bd851147d029-2542793a-49a10-1785795bf271b3; _MHYUUID=94dd314e-fd51-4c24-8a97-7e8416d5a24f; ltoken=UsSzYPwOZSSrS4FILImXL4vgp7ntMCgSKTmHt8AP; ltuid=239925102; account_id=239925102; login_ticket=T3eGQbIR6N0LgrIsFWr5KYUNUJT91rgbaRYWR5yY; cookie_token=kLl1Z5WcwAOsrKeeqR3hFBgRQjZ5QrfK601A3gL1
      x-rpc-client-type: 5
      x-requested-with: "com.mihoyo.hyperion"
      sec-fetch-site: "same-site"
      sec-fetch-mode: "cors"
      sec-fetch-dest: "empty"
      referer: "https://webstatic.mihoyo.com/"
      accept-encoding: "gzip, deflate"
      accept-language: "zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7"
      origin: "https://webstatic.mihoyo.com"
      accept: "application/json, text/plain, */*"
      user-agent: "Mozilla/5.0 (Linux; Android 9; ONEPLUS A5000 Build/PKQ1.180716.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/85.0.4183.127 Mobile Safari/537.36 miHoYoBBS/2.5.1"
